/*
 Navicat Premium Data Transfer

 Source Server         : bimeta
 Source Server Type    : PostgreSQL
 Source Server Version : 160001 (160001)
 Source Host           : localhost:5432
 Source Catalog        : bimeta
 Source Schema         : master

 Target Server Type    : PostgreSQL
 Target Server Version : 160001 (160001)
 File Encoding         : 65001

 Date: 05/03/2024 02:33:12
*/


-- ----------------------------
-- Sequence structure for m_customer_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "master"."m_customer_seq";
CREATE SEQUENCE "master"."m_customer_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for m_goods_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "master"."m_goods_id_seq";
CREATE SEQUENCE "master"."m_goods_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for m_material_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "master"."m_material_seq";
CREATE SEQUENCE "master"."m_material_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for m_production_process_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "master"."m_production_process_id_seq";
CREATE SEQUENCE "master"."m_production_process_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for m_substance_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "master"."m_substance_seq";
CREATE SEQUENCE "master"."m_substance_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for m_supplier_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "master"."m_supplier_seq";
CREATE SEQUENCE "master"."m_supplier_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for m_customer
-- ----------------------------
DROP TABLE IF EXISTS "master"."m_customer";
CREATE TABLE "master"."m_customer" (
  "id" int4 NOT NULL DEFAULT nextval('"master".m_customer_seq'::regclass),
  "code" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "address" varchar(255) COLLATE "pg_catalog"."default",
  "province_id" int4,
  "regency_id" int4,
  "district_id" int4,
  "village_id" int4,
  "phone_number" varchar COLLATE "pg_catalog"."default",
  "pic" varchar(255) COLLATE "pg_catalog"."default",
  "tax_type" varchar(255) COLLATE "pg_catalog"."default",
  "customer_type" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of m_customer
-- ----------------------------
INSERT INTO "master"."m_customer" VALUES (1571, NULL, 'ADAM', 'CIREBON', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1572, NULL, 'ADE GARUT', 'JL KEMBAR 1 NO 4', NULL, NULL, NULL, NULL, '85223262042', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1573, NULL, 'ADI', 'RUKO BLOK NO 3 BENTANG REGENCY', NULL, NULL, NULL, NULL, '81222225712', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1574, NULL, 'ADI', 'JL LEUWI SARI', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1575, NULL, 'ADIT', 'JL KOLMAS', NULL, NULL, NULL, NULL, '81221443417', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1576, NULL, 'AEP', 'JL CIBADUYUT', NULL, NULL, NULL, NULL, '81322961123', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1577, NULL, 'AGUS YUSUF', 'JL RAYA TAGOG PADALARANG', NULL, NULL, NULL, NULL, '85314708672', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1578, NULL, 'AHOK', 'JL MEKAR AGUNG NO 42 A CIBADUYUT', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1579, NULL, 'AJI', 'KP NEGLASARI GALANGGANG BATUJAJAR', NULL, NULL, NULL, NULL, '89603923046', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1580, NULL, 'AL HUSAIN PRINT', 'KP RAWA POJOK NO 38 TANIMULYA', NULL, NULL, NULL, NULL, '8', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1581, NULL, 'ALI RAHMAN', 'JL MELONG', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1582, NULL, 'AMAZING GLOBAL NIAGA', 'KP SARI RT 06 RW 02 DESA CICADAS', NULL, NULL, NULL, NULL, '811221186', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1583, NULL, 'AMIR SHAFIQ', 'JL CIATEUL NO 36', NULL, NULL, NULL, NULL, '82128129786', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1584, NULL, 'ANDHIKA ADI PUTRA', 'PINUS REGENCY NO 99', NULL, NULL, NULL, NULL, '87722400437', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1585, NULL, 'ANDINA', 'JL CANGKUANG NO 4', NULL, NULL, NULL, NULL, '8980975336', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1586, NULL, 'ANDO', 'JL KEBON SIRIH NO 75', NULL, NULL, NULL, NULL, '87878487933', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1587, NULL, 'ANDRI', 'JL CIUMBULEUIT NO 42', NULL, NULL, NULL, NULL, '88971796024', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1588, NULL, 'ANDRI KORNELIUS', 'JL CIBATU CIKUPA KM 3', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1589, NULL, 'ANGEL', 'JL HEGARASIH 2 NO 48', NULL, NULL, NULL, NULL, '8122399699', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1591, NULL, 'ANTON', 'JL CISARANTEN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1592, NULL, 'ANUGRAH MANDIRI', 'JL SANGKURIANG NO 47 CIMAHI', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1593, NULL, 'ARIS', 'JL KOPO', NULL, NULL, NULL, NULL, '81220691034', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1594, NULL, 'ARUL', 'GG BLOK TVRI 1 NO 13 CIBADUYUT', NULL, NULL, NULL, NULL, '8986145325', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1595, NULL, 'ASEHA INTERIOR', 'JL MAHMUD', NULL, NULL, NULL, NULL, '225407483', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1596, NULL, 'ASEP MOCA MULA', 'JL GALUDRA NO 4 CILAME', NULL, NULL, NULL, NULL, '82216960666', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1597, NULL, 'ASEP MOCH JAELANI', 'KOMPLEK BANJARSARI INDAH A-6', NULL, NULL, NULL, NULL, '81313161524', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1598, NULL, 'ASEP SAEPULOH', 'BUMI PANYILEUKAN BLOK K6 NO 1 CIBIRU', NULL, NULL, NULL, NULL, '81222227763', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1599, NULL, 'ASTEREXPORT', 'JL RAYA PAMUNCATAN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1600, NULL, 'AVI', 'JL BABAKN TAROGONG NO 234', NULL, NULL, NULL, NULL, '82282222126', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1601, NULL, 'AYU', 'PONDOK CIPTAMAS 2 BLOK C3 NO 25', NULL, NULL, NULL, NULL, '85280588276', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1602, NULL, 'B S C', 'JL GATOT SUBROTO', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1603, NULL, 'BAMBANG', 'JL PAGARSIH NO 63', NULL, NULL, NULL, NULL, '85222508000', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1604, NULL, 'BELEAF FARMS', 'JL RAYA BANJARAN PANGALENGAN KM 20', NULL, NULL, NULL, NULL, 'JAWA BARAT', '87878487933', '\N', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1605, NULL, 'BERKAH SAHABAT MULIA', 'JL KAV GEOLOGI BLOK 4 NO C2 CISARANTEN KULON', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1606, NULL, 'BINTANG ANUGRAH', 'JL NANJUNG', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1607, NULL, 'BINTANG JAYA', 'JL PAGARSIH 20', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1608, NULL, 'BPK PAUL', 'BANDUNG', NULL, NULL, NULL, NULL, '2', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1609, NULL, 'BUDI', 'JL SETRA MURNI', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1610, NULL, 'BUDI JAYA MOTOR', 'JL RANCABOLANG', NULL, NULL, NULL, NULL, '85700264027', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1611, NULL, 'BUDI OK', 'JL KOPO KETAPANG', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1612, NULL, 'BUDI OMEGA', 'JL KOPO', NULL, NULL, NULL, NULL, '8122329595', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1613, NULL, 'BUDI SHERISH', 'JL RANCAEKEK', NULL, NULL, NULL, NULL, '81220888240', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1614, NULL, 'BUDIANA', 'KP PASIR PANJANG KERTAJAYA', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1615, NULL, 'BUFFER STOCK', 'CIKANDANG', NULL, NULL, NULL, NULL, '-', 'STAFF', '-', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1616, NULL, 'BUNGA BAKUNG MUSIK', 'TAMAN RAHAYU BLOK G 2 / 34 MARGAASIH', NULL, NULL, NULL, NULL, '89631301864', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1617, NULL, 'BURSA PACK BANDUNG', 'JL ASTANA ANYAR NO 69', NULL, NULL, NULL, NULL, '87823482300', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1618, NULL, 'CECE FAVORS', 'CITRA GREEN DAGO J3', NULL, NULL, NULL, NULL, '81770696711', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1619, NULL, 'CEKAS', 'JL PELAJAR PEJUANG NO 85', NULL, NULL, NULL, NULL, '87722254009', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1620, NULL, 'CEPY', 'DHARMAGATI BEKANG VILA CILAME INDAH 1 NO 21', NULL, NULL, NULL, NULL, '82214136789', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1621, NULL, 'CHRISTIAN', 'BATUJAJAR REGENCY 2B BLOK AB/42', NULL, NULL, NULL, NULL, '811216681', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1622, NULL, 'CITRA BOX', 'JL NANJUNG KM 2 NO 6', NULL, NULL, NULL, NULL, '89628381819', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1623, NULL, 'CREATIVE COMPUTER', 'JL SEGITIGAMAS', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1624, NULL, 'CRONOS', 'JL CIBADAK NO 282', NULL, NULL, NULL, NULL, '83822977115', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1625, NULL, 'CV ANDIRA CAKRAWALA ABADI', 'JL RAJAWALI TIMUR', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1626, NULL, 'CV ANUGRAH', 'JL ASTANA ANYAR 176/22 A', NULL, NULL, NULL, NULL, '87823192239', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1627, NULL, 'CV ARTEMEDIA', 'JL BRAGA', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1628, NULL, 'CV BANDUNG PRINTER', 'JL SIMPANG INDUSTRI NO 10', NULL, NULL, NULL, NULL, '226120000', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1629, NULL, 'CV CAHAYA UTAMA PIRAMIDA', 'JL LIGAR AYU NO 34', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1631, NULL, 'CV CENTRAL CASTELINDO ABADI', 'JL RAYA PADALARANG', NULL, NULL, NULL, NULL, '222001423', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1632, NULL, 'CV CENTRAL DOT', 'JL PAGARSIH NO 148', NULL, NULL, NULL, NULL, '226022483', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1633, NULL, 'CV DAITA MAJU MANDIRI', 'BATUJAJAR REGENCY 2B BLOK AB NO 42', NULL, NULL, NULL, NULL, '811216681', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1634, NULL, 'CV DUTA WARNA', 'JL BETON', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1635, NULL, 'CV INDOFEED JAYA SAKTI', 'JL INSPEKSI CITARUM', NULL, NULL, NULL, NULL, '-', 'ALI', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1636, NULL, 'CV INNOVCARE TRADING', 'METRO INDAH MALL LT FF A6 NO 38', NULL, NULL, NULL, NULL, '8', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1637, NULL, 'CV IZENU JAYA', 'JL KAWALUYAAN INDAH 1 NO 4', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1638, NULL, 'CV KREA KARINA', 'JL BABAKAN CIPARAY NO 136 SUKAHAJI', NULL, NULL, NULL, NULL, '87822861730', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1639, NULL, 'CV KURNIA JAYA ABADI', 'KOMP CIMINDI RAYA', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1640, NULL, 'CV LUCAS SPS', 'JL KARANG ANYAR NO 26', NULL, NULL, NULL, NULL, '224234426', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1641, NULL, 'CV MEDIA POLAR', 'JL SURAPATI 145', NULL, NULL, NULL, NULL, '222530301', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1642, NULL, 'CV MULTI DAYA CIPTA', 'JL RUMAH SAKIT', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1643, NULL, 'CV NOORANI JAYA', 'JL ASTANA ANYAR NO 93', NULL, NULL, NULL, NULL, '81214183939', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1644, NULL, 'CV PUDAK SCIENTIFIC', 'Jl MEKAR RAYA KAV 12', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1645, NULL, 'CV PUTRA SEJATI', 'JL HOLIS', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1646, NULL, 'CV SEJAHTERA BERSAMA', 'JL GEMPOL SARI', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1647, NULL, 'CV SENTOSA ELECTRIC', 'JL HEGAR', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1648, NULL, 'CV SINAR ANUGRAH', 'BANDUNG', NULL, NULL, NULL, NULL, '8', 'LUCYANA', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1649, NULL, 'CV SINAR FAJAR', 'JL KOPO SOREANG NO 98 KM 11', NULL, NULL, NULL, NULL, 'JAWA BARAT', '-', '15888860422000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1650, NULL, 'CV SOLAN', 'KARANG ANYAR DALAM NO 3', NULL, NULL, NULL, NULL, '89512889838', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1651, NULL, 'CV SURYA BOX', 'JL SUKAMULYA', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1652, NULL, 'CV SWADAYA', 'JL INDUSTRI CIMAREME II NO 1 RT 002 RW 001 PADALARANG', NULL, NULL, NULL, NULL, '22', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1653, NULL, 'CV TANJUNG DUA', 'JL TANJUNG', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1654, NULL, 'CV TEGUH JAYA', 'JL TERUSAN PASIR KOJA NO 133', NULL, NULL, NULL, NULL, '8112399118', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1655, NULL, 'CV USAHA ABADI', 'JL MEKAR RAYA KAV 21', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1656, NULL, 'CYCIL', 'CITRA GREEN DAGO K 3', NULL, NULL, NULL, NULL, '85862096266', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1657, NULL, 'D & R', 'JL CIBADUYUT', NULL, NULL, NULL, NULL, '8122334487', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1658, NULL, 'DAVID KESHIDO', 'JL SAMPORA CILISUNG KULON NO 83A', NULL, NULL, NULL, NULL, '87833081306', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1659, NULL, 'DAVIN SENJAYA', 'JL ANDIR NO 89', NULL, NULL, NULL, NULL, '8122002470', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1660, NULL, 'DAYAT', 'JL CIMERANG', NULL, NULL, NULL, NULL, '87879848877', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1661, NULL, 'DEDE SANJAYA', 'JL PROF SUTAMI NO 99', NULL, NULL, NULL, NULL, '8112243910', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1662, NULL, 'DEDEN', 'KOMPLEK SANGGAR MAS LESTARI', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1663, NULL, 'DEDI', 'BATUJAJAR REGENCY', NULL, NULL, NULL, NULL, '87822622754', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1664, NULL, 'DELIMA PRINT', 'JL 17 AGUSTUS', NULL, NULL, NULL, NULL, '8112204321', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1665, NULL, 'DENA WIDYANA', 'GG ATAKIRIA I NO K-6 BABAKAN CIPARAY', NULL, NULL, NULL, NULL, '8', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1666, NULL, 'DENI', 'DESA KERTA WANGI NO 3', NULL, NULL, NULL, NULL, '8783134645', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1667, NULL, 'DENI', 'JL RAYA BATUJAJAR NO 90', NULL, NULL, NULL, NULL, '82117522570', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1668, NULL, 'DIAN KARMILA', 'JL PAGARSIH NO 59', NULL, NULL, NULL, NULL, '82214359124', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1669, NULL, 'DICKY', 'JL ADIWIRYA GG EYANG KASWAT NO 2', NULL, NULL, NULL, NULL, '81222886391', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1670, NULL, 'DUDI', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '81220010079', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1671, NULL, 'DUNIA MAJU', 'JL PAGARSIH 197', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1672, NULL, 'DUTA GRAFIKA', 'JL CISARANTEN KULON NO 139', NULL, NULL, NULL, NULL, '226373498', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1673, NULL, 'DUTA RASA', 'JL DJUNJUNAN PASTEUR', NULL, NULL, NULL, NULL, '22', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1674, NULL, 'DWI', 'JL CANGKUANG KULON RT 04/RW 09 DAYEUH KOLOT', NULL, NULL, NULL, NULL, '81220586670', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1675, NULL, 'EDI SILIWANGI', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '8112213078', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1676, NULL, 'EGA', 'JL PAGARSIH NO 6', NULL, NULL, NULL, NULL, '82129286039', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1677, NULL, 'ENPEKA', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1678, NULL, 'ERRIES PRINTING', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1679, NULL, 'ERWIN', 'JL BUKA NAGARA II / CLUSTER WIJAYA KUSUMA No 190 LEMBANG', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1680, NULL, 'ESTER', 'JL SEMAR NO 20', NULL, NULL, NULL, NULL, '8', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1681, NULL, 'FALENTIN', 'GADINGTUTUKA 2 BLOK K6 NO 4 SOREANG', NULL, NULL, NULL, NULL, '85220397642', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1682, NULL, 'FARAH', 'BANDUNG', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1683, NULL, 'FARHANA', 'BUKIT PERMATA CIMAHI H1 NO 48', NULL, NULL, NULL, NULL, '83836635848', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1684, NULL, 'FATCHCRAFT', 'KOPM KPAD JL ABADI RAYA 135B GEGERKALONG', NULL, NULL, NULL, NULL, '818863726', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1685, NULL, 'FERRY', 'JL TERATE', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1686, NULL, 'FITRI', 'JL CIBOLERANG', NULL, NULL, NULL, NULL, '82315316869', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1687, NULL, 'FRANSISKA', 'JL HOLIS', NULL, NULL, NULL, NULL, '8170008289', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1688, NULL, 'GAMMA JAYA', 'GG TRENA ASIH NO 2A ASTANA ANYAR', NULL, NULL, NULL, NULL, '8996094838', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1689, NULL, 'GARA', 'JL SITI MARIAH NO 215/86 JAMIKA', NULL, NULL, NULL, NULL, '81804048696', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1690, NULL, 'GHOPUR', 'JL PAGARSIH NO 83 (MANDIRI POUNCH)', NULL, NULL, NULL, NULL, '83841192875', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1691, NULL, 'GITA PRINT', 'JL RAJAWALI SAKTI', NULL, NULL, NULL, NULL, '226018023', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1692, NULL, 'GLORIOUS', 'JL SULAKSANA BARU II NO 9', NULL, NULL, NULL, NULL, '82217172217', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1693, NULL, 'GOODRICH', 'JL SOEKARNO HATTA NO 785 A', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1694, NULL, 'GRACE ROSE FARM', 'JL KOLONEL MASTURI NO 35', NULL, NULL, NULL, NULL, '22', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1695, NULL, 'GUNA PRINT', 'JL TAMAN HOLIS BLOK E2', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1696, NULL, 'HAFIZH', 'KOMP PADASUKA INDAH II BLOK F4 NO 2', NULL, NULL, NULL, NULL, '82126229767', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1697, NULL, 'HAMIZAN PRINT SHOP', 'JL PAGARSIH NO 16 RUKO PUSAT CETAK LT 2 KAV 9B', NULL, NULL, NULL, NULL, '8812286620', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1698, NULL, 'HASAN', 'GG H SITI MARDIYAH DALAM 2 NO 22', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1699, NULL, 'HENDRIYANA', 'JL SILIWANGI DLM IV NO 99/155B', NULL, NULL, NULL, NULL, '85862242310', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1700, NULL, 'HERDY', 'JL KOPO MARGAHAYU', NULL, NULL, NULL, NULL, '81320621153', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1701, NULL, 'HERI HAERUDIN', 'JL SINDANG SARI BARAT NO 32 CIMAHI SELATAN', NULL, NULL, NULL, NULL, '81322882725', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1702, NULL, 'HERI HERMAWAN', 'JL RAYA CIMAHI', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1703, NULL, 'HERLAMBANG FAJAR', 'BALTOS LT D1 NO S 08', NULL, NULL, NULL, NULL, '87824397431', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1704, NULL, 'HERRY SANTOSO', 'KOPO PERMAI 2 BLOK A5/18', NULL, NULL, NULL, NULL, '225409901', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1705, NULL, 'HJ MAMAN', 'JL BOROBUDUR', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1706, NULL, 'HJ UWAY', 'DESA PASIR MUNCANG RT 11 RW 05', NULL, NULL, NULL, NULL, '85210517587', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1707, NULL, 'IBU GRISS ( PT METRO )', 'JL MOH TOHA', NULL, NULL, NULL, NULL, '22', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1708, NULL, 'IBU IING', 'MEKAR WANGI', NULL, NULL, NULL, NULL, '8', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1709, NULL, 'ILYAS ZODA', 'JL GEGER KALONG', NULL, NULL, NULL, NULL, '8999960089', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1710, NULL, 'IMAM', 'KAMPUNG BARU LAKSANA LEMBANG', NULL, NULL, NULL, NULL, '81573151716', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1711, NULL, 'IMEL', 'JL JEND SUDIRMAN NO 151', NULL, NULL, NULL, NULL, '226658023', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1712, NULL, 'INDRA', 'JL GEGERKALONG', NULL, NULL, NULL, NULL, '81281538850', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1713, NULL, 'INDRA KISMANTO', 'JL GERLONG HILIR NO 128', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1714, NULL, 'INDRA PRATAMA', 'JL KOLONEL MASTURI NO 305', NULL, NULL, NULL, NULL, '83822516260', 'GOFAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1715, NULL, 'IRAWAN', 'JL PONDOK MAS BARU NO 9', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1716, NULL, 'IRWAN', 'JL ABDULRAHMAN SALEH NO 75', NULL, NULL, NULL, NULL, '87824806774', 'LUCYANA', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1717, NULL, 'IWA KUSDIANA', 'TAMAN CIBADUYUT INDAH BLOK L61', NULL, NULL, NULL, NULL, '87737878937', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1718, NULL, 'IYANG', 'JL PAKAR TIMUR 97', NULL, NULL, NULL, NULL, '81802299501', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1719, NULL, 'JAJANG', 'JL CIBADUYUT', NULL, NULL, NULL, NULL, '81320153969', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1720, NULL, 'JAMES', 'JL RADIO', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1721, NULL, 'JAYA CEMERLANG', 'JL MAHMUD', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1722, NULL, 'JAYA MANDIRI BOX', 'JL WANGSA PUTRA WETAN NO 18 KBP', NULL, NULL, NULL, NULL, '226803249', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1723, NULL, 'JAYA PRINT', 'JL TKI 2', NULL, NULL, NULL, NULL, '81321066028', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1724, NULL, 'JENNY MULJANI', 'JL JEND SUDIRMAN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1725, NULL, 'JHONI', 'KOMP SETIA BUDI REGENCY', NULL, NULL, NULL, NULL, '8156268958', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1726, NULL, 'JOJO', 'JL PAGARSIH NO 97', NULL, NULL, NULL, NULL, '81213429881', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1727, NULL, 'JONO', 'JL BANDUNG GARUT KM 24 WARUNG CINA RT01 RW03', NULL, NULL, NULL, NULL, '81320316312', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1728, NULL, 'JULIA', 'JL LEMBANG', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1729, NULL, 'JUSTIN OFFSET', 'JL PAGARSIH NO 12', NULL, NULL, NULL, NULL, '8562280702', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1730, NULL, 'KARTIKA SARI', 'BANDUNG', NULL, NULL, NULL, NULL, '-', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1731, NULL, 'KARYA ANUGRAH', 'JL PAGARSIH NO 29 & 102', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1732, NULL, 'KARYA HIDUP JAYANTARA', 'JL RAYA DAYEUH KOLOT NO 27', NULL, NULL, NULL, NULL, '22', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1733, NULL, 'KAYANA CIPTA', 'KOMPLEK GBA 3 BLOK P9 NO 9 BOJONGSOANG', NULL, NULL, NULL, NULL, '82118544883', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1734, NULL, 'KEMBARA', 'JL PERMATA', NULL, NULL, NULL, NULL, '8129839356', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1735, NULL, 'KIKIM', 'JL TERS CIBADUYUT', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1736, NULL, 'KO  GOAN', 'JL KOPO PERMAI', NULL, NULL, NULL, NULL, '81931467450', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1737, NULL, 'KO AWIE', 'BANDUNG', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1738, NULL, 'KOPERASI KOPASUS', 'JL BATUJAJAR', NULL, NULL, NULL, NULL, '82214446123', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1739, NULL, 'KOPERASI TRIBUANA', 'JL RAYA BATUJAJAR NO 236', NULL, NULL, NULL, NULL, '8562813446', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1740, NULL, 'KOTAKREASI', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '8562121270', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1741, NULL, 'KREASI BOX MANDIRI', 'JL MANGLID NO 21 A KOMP PERGUDANGAN NO 06', NULL, NULL, NULL, NULL, '0851 0060 3729', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1742, NULL, 'KRISTANTO', 'KAWASAN INDUSTRI GEDEBAGE', NULL, NULL, NULL, NULL, '811216681', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1743, NULL, 'KULITBATU', 'JL KH HASYIM ASHARI NO 888 CIPONDOH', NULL, NULL, NULL, NULL, '89623222600', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1744, NULL, 'KUNCORO', 'JL BUAH BATU NO 114', NULL, NULL, NULL, NULL, '82127000022', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1745, NULL, 'LASIM', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '8127224022', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1746, NULL, 'LASNO', 'JL KEBON KOPI', NULL, NULL, NULL, NULL, '8562225338', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1747, NULL, 'LESTARI PRINT', 'GG MADRASAH NO 37 PAGARSIH', NULL, NULL, NULL, NULL, '21221693992', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1748, NULL, 'LIANA', 'JL ASTANA ANYAR', NULL, NULL, NULL, NULL, '81220068687', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1749, NULL, 'LIE HWA', 'JL H IBRAHIM ADJIE', NULL, NULL, NULL, NULL, '2', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1750, NULL, 'LUMINA JAYA BOX', 'GADINGTUTUKA 2 BLOK K6 NO 4 SOREANG', NULL, NULL, NULL, NULL, '2285872817', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1751, NULL, 'LUXURY BOX', 'JL SANGKURIANG NO 70A', NULL, NULL, NULL, NULL, '89697271801', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1752, NULL, 'MAESTRO DESIGN', 'JL SUKAAMAN II NO 225/143B', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1753, NULL, 'MAHAWARNA OFFSET', 'JL PAGARSIH 83', NULL, NULL, NULL, NULL, '81381818370', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1754, NULL, 'MAMAN', 'TASIKMALAYA', NULL, NULL, NULL, NULL, '8', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1755, NULL, 'MATAHARI OFFSET PRINTING', 'JL CISIRUNG NO 136E MOH TOHA', NULL, NULL, NULL, NULL, '2242821239', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1756, NULL, 'MAY', 'JL SATRIA RAYA', NULL, NULL, NULL, NULL, '87857188561', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1757, NULL, 'MEGA JAYA', 'JL PAGARSIH 127', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1758, NULL, 'MEKAR', 'JL PAGARSIH NO 144-146', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1759, NULL, 'MOTEKAR', 'JL PAGARSIH 151', NULL, NULL, NULL, NULL, '82115644789', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1760, NULL, 'MUHTAR', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1761, NULL, 'MULIA BOX', 'JL TRS PASIR KOJA NO 112 B', NULL, NULL, NULL, NULL, '81220000121', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1762, NULL, 'NANI', 'JL PURNAWIRAWAN 3 NO 12', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1763, NULL, 'NEA', 'JL MADESA RT 05 RW 11 KOPO KEC BOJONGLOA KALER', NULL, NULL, NULL, NULL, '82133395009', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1764, NULL, 'NICKO', 'JL TIPAR', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1765, NULL, 'NIDZAR YUSNIAWAN', 'JL ALHANUARI 2 NO 20', NULL, NULL, NULL, NULL, '85173428968', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1766, NULL, 'NIK OFFSET', 'RANCAMANYAR REGENCY 2 JL MANYAR NO 32', NULL, NULL, NULL, NULL, '89679008888', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1767, NULL, 'NONI', 'BANDUNG', NULL, NULL, NULL, NULL, '-', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1768, NULL, 'NUGROSH', 'GG WARNA CINTA NO 60 MEKARWANGI', NULL, NULL, NULL, NULL, '83820121086', 'GOFAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1769, NULL, 'NUNUN', 'JL GUDANG JERO I NO 31', NULL, NULL, NULL, NULL, '8', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1770, NULL, 'NURI OFFSET', 'PLAZA PAGARSIH BLOK 1 L 9', NULL, NULL, NULL, NULL, '81297660805', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1771, NULL, 'NURPRI', 'JL CIKUTRA', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1772, NULL, 'NUSANTARA INDAH', 'JL RANCAMANYAR', NULL, NULL, NULL, NULL, '-', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1773, NULL, 'OPI PRIMA SAGA', 'KOTA BARU PARAHYANGAN', NULL, NULL, NULL, NULL, '8', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1774, NULL, 'OPICK', 'JL PAGARSIH NO 61-63', NULL, NULL, NULL, NULL, '82118174855', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1775, NULL, 'PACK MAN', 'JL PAGARSIH NO 151', NULL, NULL, NULL, NULL, '81218632797', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1776, NULL, 'PD PINO', 'JL PAMARSET NO 3', NULL, NULL, NULL, NULL, '022 4230313', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1777, NULL, 'PELANGI STEEL', 'JL SATRIA RAYA II NO 8', NULL, NULL, NULL, NULL, '225407326', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1778, NULL, 'PERCETAKAN CAHAYA', 'JL PAGARSIH NO 226', NULL, NULL, NULL, NULL, '81224785529', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1779, NULL, 'PERMADI', 'JL BKR NO 145', NULL, NULL, NULL, NULL, '8990920130', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1780, NULL, 'POD LUCKS', 'RUKO STA NIAGA BLOK B 15', NULL, NULL, NULL, NULL, '2', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1781, NULL, 'PRESTIKA DESIGN', 'TAMAN KOPO INDAH 3 RUKO D NO 28', NULL, NULL, NULL, NULL, '225414700', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1782, NULL, 'PRINT AND PACK', 'JL BABAKAN TAROGONG 244 A', NULL, NULL, NULL, NULL, '226036309', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1783, NULL, 'PRO AR', 'JL KOPO PERMAI', NULL, NULL, NULL, NULL, '81221708205', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1784, NULL, 'PT ADHIMEGA', 'JL SOEKARNO HATTA', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1785, NULL, 'PT ADIRA', 'JL BIHBUL RAYA', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1786, NULL, 'PT ALAM PARIS NUSANTARA', 'JL INHOFTANK NO 64', NULL, NULL, NULL, NULL, '85156207144', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1787, NULL, 'PT ALAMANDA', 'JL RAYA PANGALENGAN', NULL, NULL, NULL, NULL, '22', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1788, NULL, 'PT ALFA POLIMER INDONESIA', 'JL INDUSTRI CIMAREME', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1789, NULL, 'PT ALKIN GLOBAL', 'JL PASTEUR NO 15', NULL, NULL, NULL, NULL, '85314708672', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1790, NULL, 'PT ALROS', 'JL CIWARUGA', NULL, NULL, NULL, NULL, '22', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1791, NULL, 'PT AMANTRUS CIPTA MANDIRI', 'JL LEUWIGAJAH 106', NULL, NULL, NULL, NULL, '226613331', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1792, NULL, 'PT ANUGERAH KREASI', 'JL MAHMUD', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1793, NULL, 'PT AREMCI', 'JL GELAP NYAWANG', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1794, NULL, 'PT ARIANTO DARMAWAN', 'JL INDUSTRI I NO 4', NULL, NULL, NULL, NULL, '222030100', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1795, NULL, 'PT ARINDO PACIFIC CHEMICALS', 'JL RAYA MERCEDES BENZ', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1796, NULL, 'PT BANDUNG MARMER', 'JL PAMUNCATAN NO 462', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1797, NULL, 'PT BIMA BDG', 'JL ARJUNA', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1798, NULL, 'PT BIMA CSK', 'JL RAYA BARAT', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1799, NULL, 'PT BIMA POLES', 'JL RAYA BATUJAJAR', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1800, NULL, 'PT CELEBIT', 'JL BUAHDUA', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1801, NULL, 'PT CHUNG SHUN', 'JL CIGONDEWAH', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1802, NULL, 'PT CITRA MEGA NUSANTARA', 'JL PERTAMINA NO 77', NULL, NULL, NULL, NULL, '-', 'ELIS', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1803, NULL, 'PT D P L', 'JL PASANTREN', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1804, NULL, 'PT DAESE GARMIN', 'JL H IBRAHIM ADJIE', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1805, NULL, 'PT DAN LIRIS', 'KEL BANARAN KEC GROGOL', NULL, NULL, NULL, NULL, '-', 'ALI', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1806, NULL, 'PT DHANAR MAS CONCERN 1', 'JL MOCH TOHA JL CISIRUNG KEC DAYEUHKOLOT', NULL, NULL, NULL, NULL, '82219792445', 'ALI', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1807, NULL, 'PT DYMATIC CHEMICALS', 'JL CIMERANG KP CIKANDANG NO 68', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1808, NULL, 'PT ELIZABETH', 'JL MAHAR MARTANEGARA NO 105', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1809, NULL, 'PT ENERGI SURYA ANUGERAH', 'GREEN SEDAYU BIZPARK DM3 NO 31 JL DAAN MOGOT KM 18 RT 011 KALIDERES', NULL, NULL, NULL, NULL, '22', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1810, NULL, 'PT ENGGAL SUBUR KERTAS', 'JL RAYA KUDUS - PATI KM 12', NULL, NULL, NULL, NULL, 'JAWA TENGAH', '-', '-', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1811, NULL, 'PT FARMING JAYA', 'JL RADIO', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1812, NULL, 'PT FRESHLAND INOVASI SEJAHTERA', 'DESA CIMERANG NO 170 RT 002 RW 005 CIMERANG PADALARANG KAB BANDUNG BARAT JAWA BARAT', NULL, NULL, NULL, NULL, '022-86006270', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1813, NULL, 'PT GALLIARIA PROSPERA ETERNA', 'KP CIBUNGUR RT 005 RW 003 TANJUNGRASA TANJUNGSARI', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1814, NULL, 'PT GANSA ALTEXINDO', 'JL MOH TOHA NO 41', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1815, NULL, 'PT GANSA TECHNO', 'JL PETA RUKO KOPO PLAZA G/5', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1816, NULL, 'PT GELINDO GARMENTAMA', 'JL CANGKUANG KULON NO 38', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1817, NULL, 'PT GRAMER', 'JL YOS SUDARSO', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1818, NULL, 'PT HARTWELL PAINT INDONESIA', 'JL DARULIN NO 15 NANJUNG', NULL, NULL, NULL, NULL, '22', 'ALI', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1819, NULL, 'PT HEKSATEX INDAH', 'JL NANJUNG KM 2', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1820, NULL, 'PT HOLLAND FOR WATER', 'JL SOREANG-CIPATIK (CISAAT) A7 147', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1821, NULL, 'PT IDOD MULTI KREASI', 'JL BLK PASAR', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1822, NULL, 'PT INDO EVERGREEN ARGO BUSINESS', 'JL RAYA PANGALENGAN', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1823, NULL, 'PT INDO EXTRUSIONS', 'JL LEUWI GAJAH', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1824, NULL, 'PT INKO SEED MAKMUR', 'JL BUDISARI III', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1825, NULL, 'PT IPHA LABORATORIES', 'JL DESA CIBINGBIN', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1826, NULL, 'PT IWAKI GLASS INDONESIA', 'JL RAYA RANCAEKEK KM 24', NULL, NULL, NULL, NULL, 'JAWA BARAT', '-', '15553274441000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1827, NULL, 'PT JATI MEKAR', 'JL CIMUNCANG', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1828, NULL, 'PT JAVA STONE PERKASA', 'JL RAYA PAMUNCATAN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1829, NULL, 'PT KALIBARU', 'JL ARJUNA', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1830, NULL, 'PT KERTA LAKSANA', 'JL INDUSTRI II', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1831, NULL, 'PT KULIT BATU INDONESIA', 'JL PETA RUKO KOPO PLAZA BLOK G-3 BOJONG LOA KALER', NULL, NULL, NULL, NULL, '89623222600', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1832, NULL, 'PT L M B', 'JL RAYA PADALARANG', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1833, NULL, 'PT MAKMUR AGUNG PERKASA', 'JL CITRAYUDA', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1834, NULL, 'PT MARKTEL', 'JL SANGGAR KENCANA  XXVII NO 32', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1835, NULL, 'PT MASCOTINDO', 'JL MALEBER BARAT', NULL, NULL, NULL, NULL, '226034800', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1836, NULL, 'PT MASTERINDO', 'JL SOEKARNO HATTA', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1837, NULL, 'PT MEDION ARDHIKA BHAKTI', 'JL RAYA BATUJAJAR NO 29 CIMAREME', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1838, NULL, 'PT MEDION FARMA JAYA', 'JL RAYA BATUJAJAR NO 29 CIMAREME', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1839, NULL, 'PT METRO', 'JL MOH TOHA', NULL, NULL, NULL, NULL, '-', 'ALI', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1840, NULL, 'PT MICRO PAY NUSANTARA', 'JL SOEKARNO HATTA NO 269 KEBON LEGA BOJONGLOA KIDUL', NULL, NULL, NULL, NULL, '85156997466', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1841, NULL, 'PT MORIUCHI INDONESIA', 'JL CISIRUNG NO 107', NULL, NULL, NULL, NULL, '225231188', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1842, NULL, 'PT MOUNT DREAMS', 'JL PERTAMINA 77', NULL, NULL, NULL, NULL, '-', 'ELIS', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1843, NULL, 'PT MUARA GRIYA LESTARI', 'KP KADUPUGUR', NULL, NULL, NULL, NULL, '-', 'ALI', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1844, NULL, 'PT MULTI BUAH SEGAR', 'JL BIZPARK BLOK B1-51', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1845, NULL, 'PT MULTI GARMENTAMA', 'JL KOPO BIHBUL NO 103', NULL, NULL, NULL, NULL, '225400671', 'ALI', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1846, NULL, 'PT MULTI MARMER ALAM', 'JL RAYA PADALARANG', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1847, NULL, 'PT OLYMPIA', 'JL CIBADAK', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1848, NULL, 'PT PAN ASIA JAYA ABADI', 'JL MOH TOHA KM 6', NULL, NULL, NULL, NULL, 'JAWA BARAT', '-', '312779770455000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1849, NULL, 'PT PANAIRSAN PRATAMA', 'JL WIGANDA SASMITA NO 50 B', NULL, NULL, NULL, NULL, '226647489', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1850, NULL, 'PT PANTJATUNGGAL', 'JL SIMONGAN', NULL, NULL, NULL, NULL, '-', 'ALI', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1851, NULL, 'PT PELANGI WARNA KREASI', 'JL CIBOLERANG', NULL, NULL, NULL, NULL, '225422933', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1852, NULL, 'PT PRAKASA TRIPUTRA SOLUSI', 'JL SUKARNO HATTA NO 621', NULL, NULL, NULL, NULL, '81221104068', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1853, NULL, 'PT PRIMA LAKTO SEHAT', 'JL CIMERANG NO 170 KAWASAN INDUSTRI BATUJAJAR', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1854, NULL, 'PT PUDAK ORIENTAL', 'JL MEKAR RAYA KAV 12', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1855, NULL, 'PT PUDAK S', 'JL PUDAK NO 4', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1856, NULL, 'PT PUSAKA MARMER INDAHRAYA', 'BRAGA KAV B-I INA PLAZA', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1857, NULL, 'PT RENALTECH', 'JL TEMBOKAN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1858, NULL, 'PT SANLIT INTI PLASTIK', 'JL INDUSTRI III', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1859, NULL, 'PT SANSAN SAUDARATEX JAYA', 'JL CIBALIGO', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1860, NULL, 'PT SATAKI INCOTAMA', 'JL CHAIRIL ANWAR KP SEMPU', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1861, NULL, 'PT SEMESTA', 'JL KAWALUYAAN', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1862, NULL, 'PT SENI BUDAYA', 'JL HOLIS', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1863, NULL, 'PT SHERISH CIPTA  INTERINDO', 'JL PANYAWUNGAN Rt 01/ Rw 03 NO 15 CILEUNYI WETAN', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1864, NULL, 'PT SINAR RUNNERINDO', 'JL RAYA KOPO KM 12', NULL, NULL, NULL, NULL, 'JAWA BARAT', '-', '14653968445000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1865, NULL, 'PT SOLAS', 'JL INDUSTRI CIMAREME', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1866, NULL, 'PT SPARTA', 'JL RAYA DAYEUHKOLOT', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1867, NULL, 'PT SUGIH', 'JL TEMBOKAN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1868, NULL, 'PT SUNGAI BUDI', 'JL IKAN BAWAL', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1869, NULL, 'PT SUTEK MITRA UTAMA', 'JL TEMBOKAN', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1870, NULL, 'PT TERANG MAKIN MULIA', 'JL RAYA LASWI NO 99A BALEENDAH', NULL, NULL, NULL, NULL, '89681361108', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1871, NULL, 'PT TOE ZONE INDO', 'JL SADANG RAHAYU', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1872, NULL, 'PT TRIMANUNGGAL', 'JL MEKAR AGUNG', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1873, NULL, 'PT TRIMAS', 'JL RAYA KOPO KM 7', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1874, NULL, 'PT TRIMITRA GARMEDINDO', 'JL CIJERUK NO 17 LEMBANG', NULL, NULL, NULL, NULL, '2222787555', 'DAVID', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1875, NULL, 'PT TRISCO', 'JL RAYA KOPO SOREANG', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1876, NULL, 'PT TRISTAN', 'JL SOEKARNO HATTA NO 539', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1877, NULL, 'PT TRISULA', 'JL RAYA KOPO SOREANG KM 11', NULL, NULL, NULL, NULL, 'JAWA BARAT', '-', '18911982445000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1878, NULL, 'PT TUNGGAL INTI', 'JL JEND SUDIRMAN', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1879, NULL, 'PT U JUMP INDONESIA', 'KP JATIRAWING', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1880, NULL, 'PT WIJAYA ELNUSA', 'JL PAKIS  RAYA KUDUS', NULL, NULL, NULL, NULL, '0', 'ELIS', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1881, NULL, 'PT WINATA JAYA PACKINDO', 'JL TERUSAN CIBADUYUT NO 83', NULL, NULL, NULL, NULL, '8', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1882, NULL, 'PT XETRACO', 'JL NANJUNG KM 2', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1883, NULL, 'PT ZAENALCOM SERVISINDO', 'JL RS FATMAWATI NO 7A RT 002 RW 001 CIPETE UTARA', NULL, NULL, NULL, NULL, '85943500744', 'ALI', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1884, NULL, 'PT ZAMZAM ELEKTRONIK INDONESIA', 'JL CISARANTEN KULON NO 18', NULL, NULL, NULL, NULL, '81234500875', 'DEDEN', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1885, NULL, 'PT ZENTECH PRIMA KREASINDO', 'JL PUNGKUR', NULL, NULL, NULL, NULL, '-', '-', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1886, NULL, 'PT ZIEGLERINDO', 'KOMP ANGKASA MEKAR KAV 10', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1887, NULL, 'PT. PROTEKSI PUTRI MANDIRI', 'JL SADANG NO 39 CIBURUY', NULL, NULL, NULL, NULL, '81322248698', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1888, NULL, 'PUNO KAWAN', 'JL PAGARSIH NO 198A', NULL, NULL, NULL, NULL, '81222333540', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1889, NULL, 'PUTRA JAYA', 'JL PAGARSIH NO 163 CIBADAK', NULL, NULL, NULL, NULL, '87742376921', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1890, NULL, 'R S D H', 'JL JAKARTA NO 20 - 22', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1891, NULL, 'RADJAPISAU', 'JL PAGARSIH NO 49', NULL, NULL, NULL, NULL, '81809673398', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1892, NULL, 'RAGAM PRINT', 'JL ARJUNA', NULL, NULL, NULL, NULL, '-', '-', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1893, NULL, 'RAHMAT MULYANA', 'JL BAHARI KP SINDANG PALAY CANGKUANG KULON', NULL, NULL, NULL, NULL, '85943003493', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1894, NULL, 'RAHMAT SUDRAJAT', 'JL PAGARSIH NO 161', NULL, NULL, NULL, NULL, '1324051304', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1895, NULL, 'RAHMAT ZAKI', 'JL CARINGIN', NULL, NULL, NULL, NULL, '85294428465', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1896, NULL, 'RAJA KEMASAN BANDUNG', 'JL KALIDAM NO 30', NULL, NULL, NULL, NULL, '82130300698', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1897, NULL, 'RAMSA', 'JL TERS CIBADUYUT RUKO III NO 1', NULL, NULL, NULL, NULL, '85691919353', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1898, NULL, 'REKACITRA', 'JL PAMEUNGPEUK', NULL, NULL, NULL, NULL, '82115512899', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1899, NULL, 'RENI', 'JL KAMPUS VII NO 40 KIARA CONDONG', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1900, NULL, 'RIDWAN', 'JL KARANGTINEUNG INDAH 2', NULL, NULL, NULL, NULL, '222038781', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1901, NULL, 'RIDWAN C', 'JL CIKANDANG', NULL, NULL, NULL, NULL, '8', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1902, NULL, 'RIZAL', 'JL PAGARSIH NO 97', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1903, NULL, 'RONI', 'GARUT', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1904, NULL, 'RONI', 'JL CIBURUY', NULL, NULL, NULL, NULL, '89662843734', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1905, NULL, 'RS BORROMEUS', 'JL IR H JUANDA NO 100', NULL, NULL, NULL, NULL, '22', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1906, NULL, 'RUANGRUANG KREASI', 'JL MAHMUD', NULL, NULL, NULL, NULL, '225407483', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1907, NULL, 'RUBEN', 'JL NYENGSERET 68', NULL, NULL, NULL, NULL, '225208944', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1908, NULL, 'RUDY SBP GRAFIKA', 'JL PAGARSIH NO 156', NULL, NULL, NULL, NULL, '82219081999', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1909, NULL, 'RUMAH BOX', 'JL MARGAHAYU PERMAI', NULL, NULL, NULL, NULL, '8562244844', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1910, NULL, 'RUMAH DUS', 'JL CIBOLERANG NO 203 KAVLING65A MARGASUKA', NULL, NULL, NULL, NULL, '85624387669', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1911, NULL, 'S2(ESTU)', 'JL KATAPANG KULON NO 22 CILAMPENI', NULL, NULL, NULL, NULL, '89525902185', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1912, NULL, 'SAHABAT OFFSET', 'BANDUNG', NULL, NULL, NULL, NULL, '81220251982', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1913, NULL, 'SAKA BUANA', 'JL ANDIR', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1914, NULL, 'SAKATINTA', 'JL ATLAS RAYA 11C', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1915, NULL, 'SAMANTA', 'JL SADANG SARI III NO 12A', NULL, NULL, NULL, NULL, '-', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1916, NULL, 'SANTI', 'BANDUNG', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1917, NULL, 'SEFI', 'JL BATUJAJAR', NULL, NULL, NULL, NULL, '-', 'ALI', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1918, NULL, 'SEMESTA PRINT', 'JL MEKAR JAYA NO 4A', NULL, NULL, NULL, NULL, '8', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1919, NULL, 'SHOUTCAP', 'JL PASIR LAYUNG BARAT', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1920, NULL, 'SINAR AGUNG', 'JL ARJUNA', NULL, NULL, NULL, NULL, '-', '-', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1921, NULL, 'SINAR JAYA', 'JL PASIR KOJA', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V1', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1922, NULL, 'SINAR SURYA CEMERLANG', 'JL BABAKAN TAROGONG NO 83/197B', NULL, NULL, NULL, NULL, '82129111718', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1923, NULL, 'SITI', 'JL PAGARSIH NO 102', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1924, NULL, 'SOBIRIN', 'JL PAGARSIH NO 96/88', NULL, NULL, NULL, NULL, '818618054', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1925, NULL, 'SODIK', 'JL CIBADUYUT', NULL, NULL, NULL, NULL, '82214132314', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1926, NULL, 'STEVE', 'JL KARANGTINEUNG INDAH', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1927, NULL, 'STOCK BAHAN', 'JL RAYA BATUJAJAR', NULL, NULL, NULL, NULL, '-', 'STAFF', '-', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1928, NULL, 'SUGIH', 'JL HOLIS', NULL, NULL, NULL, NULL, '8122269278', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1929, NULL, 'SUGUH', 'JL BLOK BEAS CARINGIN', NULL, NULL, NULL, NULL, '8121460501', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1930, NULL, 'SUHE', 'JL KEBON JAYANTI NO 118 KIRCON', NULL, NULL, NULL, NULL, '81222884434', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1931, NULL, 'SUHENDAR', 'JL SUKARASA NO 34 RT 05 RW 11', NULL, NULL, NULL, NULL, '82120039782', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1932, NULL, 'SUMBER REZEKI', 'JL BABAKAN TAROGONG', NULL, NULL, NULL, NULL, '81386302445', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1933, NULL, 'SURYANTI', 'KOPO PERMAI 1 BLOK S NO 25', NULL, NULL, NULL, NULL, '811210494', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1934, NULL, 'TANI MURNI', 'JL PASKAL NO 112', NULL, NULL, NULL, NULL, '81122202224', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1935, NULL, 'TEGUH', 'JL PAGARSIH 4A', NULL, NULL, NULL, NULL, '-', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1936, NULL, 'TENTI', 'JL SEMAR NO 20', NULL, NULL, NULL, NULL, '85103477005', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1937, NULL, 'TINO', 'JL PAGARSIH 115', NULL, NULL, NULL, NULL, '-', '-', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1938, NULL, 'TITO', 'JL SOMAWINATA NO 124 TANIMULYA', NULL, NULL, NULL, NULL, '85320104654', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1939, NULL, 'TJINSAN', 'JL TAMAN HOLIS INDAH 1 D2 NO 55', NULL, NULL, NULL, NULL, '8122004087', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1940, NULL, 'TONO SANJAYA', 'JL PAGARSIH NO 147', NULL, NULL, NULL, NULL, '82214157682', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1941, NULL, 'TONY', 'BANDUNG', NULL, NULL, NULL, NULL, '8552177888', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1942, NULL, 'TRIANI', 'GG EKA WARGA I NO 19 - KOPO', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1943, NULL, 'TRINITI MEDIA GRAFIKA', 'JL TERUSAN H ALPI NO 106', NULL, NULL, NULL, NULL, '228603504', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1944, NULL, 'TUMIJO', 'JL MENGGER HILIR DEPAN NO 101', NULL, NULL, NULL, NULL, '81221013270', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1945, NULL, 'UJANG SUPRIATNA', 'JL NANJUNG', NULL, NULL, NULL, NULL, '9663172435', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1946, NULL, 'UNIVERSAL ( RICHAD )', 'JL SATRIA RAYA III NO 5', NULL, NULL, NULL, NULL, '-', '-', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1947, NULL, 'UYAN', 'NANGEWER RT 02 RW 18 DESA BATULAYANG CILILIN', NULL, NULL, NULL, NULL, '82111734823', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1948, NULL, 'VERA', 'CIMERANG RT 01 RW 02 GG NANGKA NO 11', NULL, NULL, NULL, NULL, '85221490661', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1949, NULL, 'VINCENT', 'JL SETIABUDI NO 45', NULL, NULL, NULL, NULL, '811200285', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1950, NULL, 'VOSKA', 'JL BATIK KUMELI NO 32 SUKALUYU', NULL, NULL, NULL, NULL, '81221533927', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1951, NULL, 'WIBOWO', 'JL SUKAJADI 215 A', NULL, NULL, NULL, NULL, '85221004788', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1952, NULL, 'WIDJI MULTI KREASINDO', 'JL SUKAMENAK NO 168 A', NULL, NULL, NULL, NULL, '81222200100', 'DAVID', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1953, NULL, 'WULAN', 'JL SRI WIJAYA 2 NO F4', NULL, NULL, NULL, NULL, '8', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1954, NULL, 'YANI', 'JL LEUWI PANJANG', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1955, NULL, 'YENNI', 'JL SADANG NO 39 RT 02/16', NULL, NULL, NULL, NULL, '81221589918', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1956, NULL, 'YON-YON', 'JL PAGARSIH NO 16 PCP 16 LT 1 NO 4', NULL, NULL, NULL, NULL, '-', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1957, NULL, 'YUDA', 'JL PAGARSIH', NULL, NULL, NULL, NULL, '8', 'DEDEN', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1958, NULL, 'YUDI', 'KOMP BUMI PAKUSARAKAN C1 NO 7', NULL, NULL, NULL, NULL, '-', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1959, NULL, 'YUDO', 'JL CIPAMOKOLAN DERWATI NO 57', NULL, NULL, NULL, NULL, '81218495141', 'GOPAR', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1960, NULL, 'YUNUS', 'JL HEGAR MANAH NO 63', NULL, NULL, NULL, NULL, '8', 'AHMAD', 'V2', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_customer" VALUES (1630, 'CR', 'CV CARIN INTERNATIONAL', 'JL CARINGIN NO 37B', NULL, NULL, NULL, NULL, '225404119', 'ali', 'V1', NULL, NULL, NULL, '2024-01-23 16:10:45', 'ali');
INSERT INTO "master"."m_customer" VALUES (1570, 'AS', 'ABADI SENTOSA', 'JL H SAFARI SILIH ASIH NO 5', NULL, NULL, NULL, NULL, '85860180550', 'ALI', 'V1', 'PERSONAL', NULL, NULL, '2024-01-24 14:03:26', 'ALI');
INSERT INTO "master"."m_customer" VALUES (1590, NULL, 'ANGGA', 'JL PAGARSIH NO 97', NULL, NULL, NULL, NULL, '-', NULL, 'V1', NULL, NULL, NULL, '2024-02-29 10:11:59', 'ALI');

-- ----------------------------
-- Table structure for m_goods
-- ----------------------------
DROP TABLE IF EXISTS "master"."m_goods";
CREATE TABLE "master"."m_goods" (
  "id" int4 NOT NULL DEFAULT nextval('"master".m_goods_id_seq'::regclass),
  "type" int2,
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "ply_type" varchar(255) COLLATE "pg_catalog"."default",
  "flute_type" varchar(255) COLLATE "pg_catalog"."default",
  "substance" varchar(255) COLLATE "pg_catalog"."default",
  "meas_unit" varchar(53) COLLATE "pg_catalog"."default",
  "meas_type" varchar(53) COLLATE "pg_catalog"."default",
  "length" float8,
  "width" float8,
  "height" float8,
  "top_ply_type" varchar(255) COLLATE "pg_catalog"."default",
  "top_flute_type" varchar(255) COLLATE "pg_catalog"."default",
  "top_substance" varchar(255) COLLATE "pg_catalog"."default",
  "top_meas_unit" varchar(255) COLLATE "pg_catalog"."default",
  "top_length" float8,
  "top_width" float8,
  "top_height" float8,
  "bottom_ply_type" varchar(255) COLLATE "pg_catalog"."default",
  "bottom_flute_type" varchar(255) COLLATE "pg_catalog"."default",
  "bottom_substance" varchar(255) COLLATE "pg_catalog"."default",
  "bottom_meas_unit" varchar(255) COLLATE "pg_catalog"."default",
  "bottom_length" float8,
  "bottom_width" float8,
  "bottom_height" float8,
  "created_at" timestamp(6),
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default",
  "price" numeric(10,2),
  "top_price" numeric(10,2),
  "bottom_price" numeric(10,2)
)
;

-- ----------------------------
-- Records of m_goods
-- ----------------------------
INSERT INTO "master"."m_goods" VALUES (2, 1, 'SHEET', 'SF', 'E', 'SF ALLMED', 'MM', NULL, 125, 150, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-18 12:58:57', 'ali', NULL, NULL, 3000.00, NULL, NULL);
INSERT INTO "master"."m_goods" VALUES (3, 3, 'BOX BADAN TUTUP (AB)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SW', 'B', 'SF ALLMED', 'CM', 15, 15, 15, 'SF', 'B', 'SF ALLMED', 'CM', 15, 15, 15, '2024-01-18 13:01:31', 'ali', NULL, NULL, NULL, 3500.00, 4500.00);
INSERT INTO "master"."m_goods" VALUES (4, 4, 'BOX BADAN TUTUP (BB)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SF', 'B', 'SF ALLMED', 'CM', 15, 15, 15, 'SF', 'B', 'WK/M', 'CM', 10, 20, 20, '2024-01-18 13:03:03', 'ali', NULL, NULL, NULL, 2500.00, 2300.00);
INSERT INTO "master"."m_goods" VALUES (6, 2, 'CARTON/LAYER', 'DW', 'B', '200K/M3/200K', 'CM', 'UL', 85, 53, 27, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-19 16:47:15', 'ali', NULL, NULL, 0.00, NULL, NULL);
INSERT INTO "master"."m_goods" VALUES (7, 1, 'CARTON/LAYER', 'SW', 'B', 'SW ALLMED', 'CM', NULL, 82, 51, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-19 16:51:53', 'ali', NULL, NULL, 0.00, NULL, NULL);
INSERT INTO "master"."m_goods" VALUES (5, 1, 'CARTON/LAYER', 'DW', 'B', '200K/M3/200K', 'CM', 'UL', 85, 53, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-19 16:44:56', 'ali', '2024-01-21 13:49:25', 'ali', 0.00, NULL, NULL);
INSERT INTO "master"."m_goods" VALUES (8, 1, 'LAYER K200', 'SW', 'B', '125K/M/125K', 'CM', NULL, 35.8, 27.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-30 17:26:54', 'ALI', NULL, NULL, 641.00, NULL, NULL);
INSERT INTO "master"."m_goods" VALUES (9, 2, 'BOX SAMPLE PARFUME', 'SW', 'B', '125K/M/125K', 'CM', 'UL', 30.5, 15, 20, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-02-04 06:26:09', 'ALI', NULL, NULL, 0.00, NULL, NULL);
INSERT INTO "master"."m_goods" VALUES (1, 2, 'BOX', 'SW', 'B', '125K/M/125K', 'CM', 'UL', 15, 17.5, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-18 12:58:04', 'ali', '2024-02-26 04:27:34', 'ALI', 1290.00, NULL, NULL);

-- ----------------------------
-- Table structure for m_material
-- ----------------------------
DROP TABLE IF EXISTS "master"."m_material";
CREATE TABLE "master"."m_material" (
  "id" int8 NOT NULL DEFAULT nextval('"master".m_material_seq'::regclass),
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "type" varchar(255) COLLATE "pg_catalog"."default",
  "paper_type" varchar(255) COLLATE "pg_catalog"."default",
  "gramature" varchar(255) COLLATE "pg_catalog"."default",
  "unit" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6),
  "updated_by" varchar COLLATE "pg_catalog"."default",
  "code" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of m_material
-- ----------------------------
INSERT INTO "master"."m_material" VALUES (19, 'KRAFT 150', 'KRAFT', 'BROWN KRAFT', '150', 'GSM', '2024-02-26 06:23:17', 'ALI', NULL, NULL, 'K150');
INSERT INTO "master"."m_material" VALUES (20, 'KRAFT 200', 'KRAFT', 'BROWN KRAFT', '200', 'GSM', '2024-02-26 06:23:42', 'ALI', NULL, NULL, 'K200');
INSERT INTO "master"."m_material" VALUES (21, 'KRAFT 275', 'KRAFT', 'BROWN KRAFT', '275', 'GSM', '2024-02-26 06:24:08', 'ALI', NULL, NULL, 'K275');
INSERT INTO "master"."m_material" VALUES (22, 'KRAFT 300', 'KRAFT', 'BROWN KRAFT', '300', 'GSM', '2024-02-26 06:24:30', 'ALI', NULL, NULL, 'K300');
INSERT INTO "master"."m_material" VALUES (23, 'TL 125', 'KRAFT', 'TEST LINER', '125', 'GSM', '2024-02-26 06:25:44', 'ALI', NULL, NULL, 'TL125');
INSERT INTO "master"."m_material" VALUES (24, 'TL 150', 'KRAFT', 'TEST LINER', '150', 'GSM', '2024-02-26 06:26:12', 'ALI', NULL, NULL, 'TL150');
INSERT INTO "master"."m_material" VALUES (25, 'WK 150', 'KRAFT', 'WHITE KRAFT', '150', 'GSM', '2024-02-26 06:26:50', 'ALI', NULL, NULL, 'WK150');
INSERT INTO "master"."m_material" VALUES (26, 'WK 200', 'KRAFT', 'WHITE KRAFT', '200', 'GSM', '2024-02-26 06:27:15', 'ALI', NULL, NULL, 'WK200');
INSERT INTO "master"."m_material" VALUES (27, 'M 125', 'MEDIUM', 'MEDIUM', '125', 'GSM', '2024-02-26 06:27:46', 'ALI', NULL, NULL, 'M125');
INSERT INTO "master"."m_material" VALUES (28, 'M 150', 'MEDIUM', 'MEDIUM', '150', 'GSM', '2024-02-26 06:28:09', 'ALI', NULL, NULL, 'M150');
INSERT INTO "master"."m_material" VALUES (18, 'KRAFT 125 PK', 'KRAFT', 'BROWN KRAFT', '125', 'GSM', '2024-02-26 06:22:47', 'ALI', '2024-03-01 04:17:38', 'ALI', NULL);

-- ----------------------------
-- Table structure for m_production_process
-- ----------------------------
DROP TABLE IF EXISTS "master"."m_production_process";
CREATE TABLE "master"."m_production_process" (
  "id" int4 NOT NULL DEFAULT nextval('"master".m_production_process_id_seq'::regclass),
  "process_name" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of m_production_process
-- ----------------------------
INSERT INTO "master"."m_production_process" VALUES (1, 'COR', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (2, 'SLITTER', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (3, 'SLOTTER', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (4, 'FLEXO', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (5, 'LONGWAY', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (6, 'PRINT SLOT', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (7, 'COAK', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (8, 'POUNCH', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (9, 'TRIPLE', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (10, 'LAMINASI', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (11, 'KANCING', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (12, 'KUPAS', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (13, 'LEM', NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_production_process" VALUES (14, 'MUAT', NULL, NULL, NULL, NULL);

-- ----------------------------
-- Table structure for m_substance
-- ----------------------------
DROP TABLE IF EXISTS "master"."m_substance";
CREATE TABLE "master"."m_substance" (
  "id" int4 NOT NULL DEFAULT nextval('"master".m_substance_seq'::regclass),
  "code" varchar(255) COLLATE "pg_catalog"."default",
  "substance" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6),
  "updated_by" varchar COLLATE "pg_catalog"."default",
  "cor_code" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of m_substance
-- ----------------------------
INSERT INTO "master"."m_substance" VALUES (69, 'SW ALLMED TL', '125M3 TL', '2024-01-20 14:47:31', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (70, 'DW ALLMED TL', '125M5 TL', '2024-01-20 14:48:26', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (71, '125K/M TL', '125K/125M TL', '2024-01-20 14:50:33', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (72, '125K/M/125K TL', '125K/125M/125K TL', '2024-01-20 14:51:06', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (73, '125K/M2 TL', '125K/125M2 TL', '2024-01-20 14:51:26', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (74, '125K/125M3/125K TL', '125K/125M3/125K TL', '2024-01-20 14:51:38', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (75, '125K/M4 TL', '125K/125M4 TL', '2024-01-20 14:51:58', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (76, '125K/M5/125K TL', '125K/125M5/125K TL', '2024-01-20 14:52:10', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (77, '125K/M6 TL', '125K/125M6 TL', '2024-01-20 14:52:24', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (78, '150K/M/125K TL', '150K/125M/125K TL', '2024-01-20 14:52:36', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (79, '150K/M/150K TL', '150K/125M/150K TL', '2024-01-20 14:53:00', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (80, '150K/M2 TL', '150K/125M2 TL', '2024-01-20 14:53:17', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (81, '150K/M3/125K TL', '150K/125M3/125K TL', '2024-01-20 14:53:32', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (82, '150K/M3/150K TL', '150K/125M3/150K TL', '2024-01-20 14:53:43', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (83, '150K/M4 TL', '150K/125M4 TL', '2024-01-20 14:53:53', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (84, '150WK/M TL', '150WK/125M TL', '2024-01-20 14:54:06', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (85, '150WK/M/125K TL', '150WK/125M/125K TL', '2024-01-20 14:54:16', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (86, '150WK/M/150K TL', '150WK/125M/150K TL', '2024-01-20 14:54:26', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (87, '150WK/M/150WK TL', '150WK/125M/150WK TL', '2024-01-20 14:54:36', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (88, '150WK/M2 TL', '150WK/125M2 TL', '2024-01-20 14:54:53', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (89, '150WK/M3/150WK TL', '150WK/125M3/150WK TL', '2024-01-20 14:55:04', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (90, '150WK/M4 TL', '150WK/125M4 TL', '2024-01-20 14:55:14', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (91, '200K/M/125K TL', '200K/125M/125K TL', '2024-01-20 14:55:25', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (92, '200K/M/150K TL', '200K/125M/150K TL', '2024-01-20 14:55:35', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (93, '200K/M/200K TL', '200K/125M/200K TL', '2024-01-20 14:55:46', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (94, '200K/M2 TL', '200K/125M2 TL', '2024-01-20 14:55:58', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (95, '200K/M3/125K TL', '200K/125M3/125K TL', '2024-01-20 14:56:10', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (96, '200K/M3/150K TL', '200K/125M3/150K TL', '2024-01-20 14:56:44', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (97, '200K/M3/200K TL', '200K/125M3/200K TL', '2024-01-20 14:57:13', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (98, '200K/M4 TL', '200K/125M4 TL', '2024-01-20 14:57:24', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (99, '200WK/M3/200K TL', '200WK/125M3/200K TL', '2024-01-20 14:57:35', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (36, 'SW ALLMED', '125M3', '2024-01-20 14:29:40', 'ali', NULL, NULL, '+++');
INSERT INTO "master"."m_substance" VALUES (37, 'DW ALLMED', '125M5', '2024-01-20 14:30:40', 'ali', NULL, NULL, '+++++');
INSERT INTO "master"."m_substance" VALUES (60, '200K/M/200K', '200K/125M/200K', '2024-01-20 14:35:31', 'ali', NULL, NULL, 'D+D');
INSERT INTO "master"."m_substance" VALUES (61, '200K/M2', '200K/125M2', '2024-01-20 14:35:42', 'ali', NULL, NULL, 'D++');
INSERT INTO "master"."m_substance" VALUES (62, '200K/M3/125K', '200K/125M3/125K', '2024-01-20 14:35:51', 'ali', NULL, NULL, 'D+++A');
INSERT INTO "master"."m_substance" VALUES (63, '200K/M3/150K', '200K/125M3/150K', '2024-01-20 14:36:03', 'ali', NULL, NULL, 'D+++C');
INSERT INTO "master"."m_substance" VALUES (64, '200K/M3/200K', '200K/125M3/200K', '2024-01-20 14:36:14', 'ali', NULL, NULL, 'D+++D');
INSERT INTO "master"."m_substance" VALUES (65, '200K/M4', '200K/125M4', '2024-01-20 14:37:15', 'ali', NULL, NULL, 'D++++');
INSERT INTO "master"."m_substance" VALUES (100, 'TEST', 'TEST', '2024-01-23 14:47:06', 'ali', NULL, NULL, 'TEST');
INSERT INTO "master"."m_substance" VALUES (38, '125M/M', '125K/125M', '2024-01-20 14:30:55', 'ali', NULL, NULL, 'A+');
INSERT INTO "master"."m_substance" VALUES (35, 'SF ALLMED', '125M2', '2024-01-20 14:25:28', 'ali', NULL, NULL, '++');
INSERT INTO "master"."m_substance" VALUES (66, '200WK/M3/200K', '200WK/125M3/200K', '2024-01-20 14:40:14', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (67, '300K/M3/300K', '300K/125M3/300K', '2024-01-20 14:41:04', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (68, 'SF ALLMED TL', '125M2 TL', '2024-01-20 14:46:00', 'ali', NULL, NULL, NULL);
INSERT INTO "master"."m_substance" VALUES (39, '125K/M/125K', '125K/125M/125K', '2024-01-20 14:31:10', 'ali', NULL, NULL, 'A+A');
INSERT INTO "master"."m_substance" VALUES (40, '125K/M2', '125K/125M2', '2024-01-20 14:31:22', 'ali', NULL, NULL, 'A++');
INSERT INTO "master"."m_substance" VALUES (41, '125K/M3/125K', '125K/125M3/125K', '2024-01-20 14:31:35', 'ali', NULL, NULL, 'A+++A');
INSERT INTO "master"."m_substance" VALUES (42, '125K/M4', '125K/125M4', '2024-01-20 14:31:48', 'ali', NULL, NULL, 'A++++');
INSERT INTO "master"."m_substance" VALUES (43, '125K/M5/125K', '125K/125M5/125K', '2024-01-20 14:32:00', 'ali', NULL, NULL, 'A+++++A');
INSERT INTO "master"."m_substance" VALUES (44, '125K/M6', '125K/125M6', '2024-01-20 14:32:12', 'ali', NULL, NULL, 'A++++++');
INSERT INTO "master"."m_substance" VALUES (45, '150K/M/125K', '150K/125M/125K', '2024-01-20 14:32:23', 'ali', NULL, NULL, 'C+A');
INSERT INTO "master"."m_substance" VALUES (46, '150K/M/150K', '150K/125M/150K', '2024-01-20 14:32:36', 'ali', NULL, NULL, 'C+C');
INSERT INTO "master"."m_substance" VALUES (47, '150K/M2', '150K/125M2', '2024-01-20 14:32:48', 'ali', NULL, NULL, 'C++');
INSERT INTO "master"."m_substance" VALUES (48, '150K/M3/125K', '150K/125M3/125K', '2024-01-20 14:33:05', 'ali', NULL, NULL, 'C+++A');
INSERT INTO "master"."m_substance" VALUES (49, '150K/M3/150K', '150K/125M3/150K', '2024-01-20 14:33:18', 'ali', NULL, NULL, 'C+++C');
INSERT INTO "master"."m_substance" VALUES (50, '150K/M4', '150K/125M4', '2024-01-20 14:33:30', 'ali', NULL, NULL, 'C++++');
INSERT INTO "master"."m_substance" VALUES (51, '150WK/125M', '150WK/125M', '2024-01-20 14:33:42', 'ali', NULL, NULL, 'WK+');
INSERT INTO "master"."m_substance" VALUES (52, '150WK/M/125K', '150WK/125M/125K', '2024-01-20 14:33:54', 'ali', NULL, NULL, 'WK+A');
INSERT INTO "master"."m_substance" VALUES (53, '150WK/1M/150K', '150WK/125M/150K', '2024-01-20 14:34:06', 'ali', NULL, NULL, 'WK+C');
INSERT INTO "master"."m_substance" VALUES (54, '150WK/M/150WK', '150WK/125M/150WK', '2024-01-20 14:34:19', 'ali', NULL, NULL, 'WK+WK');
INSERT INTO "master"."m_substance" VALUES (55, '150WK/M2', '150WK/125M2', '2024-01-20 14:34:30', 'ali', NULL, NULL, 'WK++');
INSERT INTO "master"."m_substance" VALUES (56, '150WK/M3/150WK', '150WK/125M3/150WK', '2024-01-20 14:34:41', 'ali', NULL, NULL, 'WK+++WK');
INSERT INTO "master"."m_substance" VALUES (57, '150WK/M4', '150WK/125M4', '2024-01-20 14:34:54', 'ali', NULL, NULL, 'WK++++');
INSERT INTO "master"."m_substance" VALUES (58, '200K/M/125K', '200K/125M/125K', '2024-01-20 14:35:06', 'ali', NULL, NULL, 'D+A');
INSERT INTO "master"."m_substance" VALUES (59, '200K/M/150K', '200K/125M/150K', '2024-01-20 14:35:18', 'ali', NULL, NULL, 'D+C');

-- ----------------------------
-- Table structure for m_supplier
-- ----------------------------
DROP TABLE IF EXISTS "master"."m_supplier";
CREATE TABLE "master"."m_supplier" (
  "id" int8 NOT NULL DEFAULT nextval('"master".m_supplier_seq'::regclass),
  "code" varchar(255) COLLATE "pg_catalog"."default",
  "name" varchar(255) COLLATE "pg_catalog"."default",
  "address" varchar(255) COLLATE "pg_catalog"."default",
  "province_id" int8,
  "regency_id" int8,
  "district_id" int8,
  "village_id" int8,
  "phone_number" int8,
  "pic" varchar(255) COLLATE "pg_catalog"."default",
  "tax_type" varchar(255) COLLATE "pg_catalog"."default",
  "created_at" timestamp(6),
  "created_by" varchar(255) COLLATE "pg_catalog"."default",
  "updated_at" timestamp(6),
  "updated_by" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Records of m_supplier
-- ----------------------------
INSERT INTO "master"."m_supplier" VALUES (1, 'CIK', 'PT CAKRAWALA INDAH KIAT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (2, 'CMN', 'PT CITRA MEGA NUSANTARA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (4, 'MDI', 'PT MOUNT DREAMS INDONESIA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (5, 'PB', 'PT PURA BARUTAMA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (6, 'PK', 'PT PAKERIN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (8, 'SGB', 'PT SHINE GOLDEN BRIDGE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (9, 'SI', 'PT SINAR INDAH KERTAS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (10, 'SPM', 'PT SUMBER PELITA MAKMUR', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (11, 'SPS', 'PT STAR PAPER SUPPLY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "master"."m_supplier" VALUES (13, 'SUP-0001', 'PT INDEX PERKASA', 'BANDUNG', NULL, NULL, NULL, NULL, 88989, 'KENEDY', 'V1', '2024-01-23 14:36:22', 'ali', '2024-01-23 16:19:19', 'ali');
INSERT INTO "master"."m_supplier" VALUES (7, 'PS', 'PT PELANGI STEEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2024-01-25 18:26:14', 'ALI');
INSERT INTO "master"."m_supplier" VALUES (3, 'ESK', 'PT ENGGAL SUBUR KERTAS', 'JL. RAYA KUDUS - PATI KM. 12.5 KUDUS 59382', NULL, NULL, NULL, NULL, 291424611923, NULL, 'V0', NULL, NULL, '2024-02-29 11:04:26', 'ALI');

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"master"."m_customer_seq"', 1960, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"master"."m_goods_id_seq"', 9, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"master"."m_material_seq"', 28, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"master"."m_production_process_id_seq"', 14, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"master"."m_substance_seq"', 100, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"master"."m_supplier_seq"', 13, true);

-- ----------------------------
-- Primary Key structure for table m_customer
-- ----------------------------
ALTER TABLE "master"."m_customer" ADD CONSTRAINT "m_customer_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table m_goods
-- ----------------------------
ALTER TABLE "master"."m_goods" ADD CONSTRAINT "m_goods_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table m_material
-- ----------------------------
ALTER TABLE "master"."m_material" ADD CONSTRAINT "m_material_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table m_production_process
-- ----------------------------
ALTER TABLE "master"."m_production_process" ADD CONSTRAINT "m_process_poduction_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table m_substance
-- ----------------------------
ALTER TABLE "master"."m_substance" ADD CONSTRAINT "m_substance_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table m_supplier
-- ----------------------------
ALTER TABLE "master"."m_supplier" ADD CONSTRAINT "m_supplier_pkey" PRIMARY KEY ("id");
